name: Validate Home Assistant YAML

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-yaml:
    name: Check YAML Syntax
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Lint YAML files
        run: |
          yamllint automations/
          yamllint blueprints/
          yamllint dashboards/